.github/CODEOWNERS, common.go, go.mod, semconvgen/README.md, semconvgen/generator.go, semconvgen/go.mod, semconvgen/go.sum
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
=> Add semconvgen

semconvgen/generator.go
Sorry, this should have been committed along with #3; the "path/filepath" import statement needs to be removed, too! Thanks 😄
=> Removed unused import

semconvgen/generator.go
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
=> semconvgen: pass parameters through to template renderer

multimod/internal/prerelease/prerelease.go, multimod/internal/prerelease/prerelease_test.go
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
=> Ensure multimod prerelease can rewrite versions for indirect module deps

dbotconf/go.mod
Updates the psuedo-version of the `build-tools` import.
=> Update build-tools psuedo version

crosslink/go.mod, dbotconf/go.mod, internal/tools/go.mod, multimod/go.mod, semconvgen/go.mod, semconvgen/go.sum
Updates psuedo versions to latest.
=> Update pseudo versions of go-build-tools

multimod/go.mod, multimod/go.sum, multimod/internal/common/tools.go
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
=> Use `-compat=1.17` when tidying modules in multimod

crosslink/cmd/root.go, dbotconf/internal/mods.go, internal/repo/repo.go, internal/repo/repo_test.go, multimod/cmd/root.go, multimod/internal/prerelease/prerelease.go, multimod/internal/sync/sync.go, multimod/internal/tag/tag.go, multimod/internal/verify/verify.go
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>
=> Remove unnecessary public API, move to internal

Makefile
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>
=> Add makefile rule to add tags, inspired by otel-go

.chloggen/tagPush.yaml, multimod/README.md, multimod/cmd/tag.go, multimod/internal/tag/tag.go, multimod/internal/tag/tag_test.go
Closes #157 
Add the ability for multimod to automatically publish tags by providing the `--push` flag.
=> [multimod] Add ability for multimod to push tags automatically 

Makefile
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>
=> [chore] fix push-tag command, used to do v0.2.0 release

.github/workflows/scripts/dependabot-pr.sh
=> [chore] fix line check in dependabot script

chloggen/cmd/cmd_test.go, chloggen/cmd/new.go, chloggen/cmd/root.go, chloggen/cmd/update_test.go, chloggen/cmd/validate.go, chloggen/internal/chlog/context.go, chloggen/internal/chlog/context_test.go, chloggen/internal/chlog/entry.go, chloggen/internal/chlog/entry_test.go
This PR contains some minor variable renaming and standardization in the chloggen package. I am working towardsmore meaningful changes but found several inconsistencies that seemed worth ironing out first.
=> [chore][chloggen] Clean up terminology for unreleased directory

.chloggen/add-component-validation.yaml, .chloggen/add-prefix-validation.yaml, chloggen/cmd/validate.go, chloggen/cmd/validate_test.go, chloggen/internal/chlog/entry.go, chloggen/internal/chlog/entry_test.go, chloggen/internal/config/config.go, chloggen/internal/config/config.yaml
=> chloggen: add component validation

Makefile, internal/tools/go.mod, internal/tools/go.sum, internal/tools/tools.go
=> [chore] add govulncheck

checkapi/internal/ast.go, checkapi/internal/ast_test.go, checkapi/internal/badpkg/receiver/bad2receiver/code_test.go, checkapi/internal/config.go, checkapi/main.go
This adds generics support when outputting function signatures.
=> [chore] support generics

Makefile
- Add MOQ dependency on generate target.
- Run generate prior to any linting for valid check.
- Run crosslink prior to linting and generate to ensure dependency resolution.
=> Fix generate target

renovate.json
This requires enablement via the OpenTelemetry org once this is merged.
=> Switch to Renovate

renovate.json
Try to group dep updates together, mostly copied from -contrib https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/renovate.json
=> [chore] Update renovate.json

issuegenerator/main.go
There were a couple keys being used repeatedly here that could be made into consts to reduce the chance of typos and errors.
=> [chore][issuegenerator] Move strings to consts

.chloggen/multimod-root-cmd-name.yaml, multimod/cmd/root.go
Ensure the multimod command displays the correct name for help text.
Resolve #991
=> Update multimod root command name.

.chloggen/deprecate-semconvgen.yaml, semconvgen/README.md, semconvgen/go.mod
=> Deprecate semconvgen

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement.yml
=> Add issue templates
