open-telemetry/opentelemetry-go-build-tools

semconvgen/generator.go

Seems like the function `findRepoRoot` was duplicated in the `semconvgen/generator.go` file and is unused in favor of the common `tools.FindRepoRoot` func.

Removed duplicated local definition of findRepoRoot

---

.gitignore

Adds crosslink to gitignore. Was missed in PR split.

Add crosslink to gitignore

---

crosslink/cmd/root.go

This PR changes how the command config is created to address a bug where `DefaultRunConfig` was never called. Command config creation is now bundled into `newCommandConfig` where commands are added and a run config is created.

Change command config creation logic

---

crosslink/README.md
crosslink/cmd/root.go
crosslink/cmd/root_test.go
crosslink/internal/common.go
crosslink/internal/crosslink_test.go

This PR fixes an issue in crosslink where the default root path was not correctly set if the `--root` flag was not provided. The tests were also adjusted to account for this issue.

Set rootPath to cwd

---

.github/CODEOWNERS
.github/dependabot.yml
.github/workflows/markdown.yml
.gitignore
chloggen/README.md
chloggen/context.go
chloggen/entry.go
chloggen/go.mod
chloggen/go.sum
chloggen/main.go
chloggen/main_test.go
chloggen/summary.go
chloggen/summary.tmpl
chloggen/testdata/CHANGELOG.md
chloggen/testdata/all_change_types.md
chloggen/testdata/all_change_types_multiple.md
chloggen/testdata/breaking_only.md
chloggen/testdata/bug_fix_only.md
chloggen/testdata/deprecation_only.md
chloggen/testdata/dry_run.md
chloggen/testdata/enhancement_only.md
chloggen/testdata/new_component_only.md
chloggen/testdata/subtext.md
chloggen/testdata/unreleased/TEMPLATE.yaml

This tool is used in the OpenTelemetry collector repositories to generate the changelog from a set of YAML files. The reason for moving this tool here is to make it available for both collector and collector contrib repos.

add chloggen tool

---

chloggen/context.go
chloggen/main.go
chloggen/summary.go

This change allows chloggen to find the `unreleased` folder in the current directory, rather than expecting it to be in the module's directory. Also added a validation check for the filename on `new` command.

[chloggen] use current directory as repo root

---

.github/CODEOWNERS

- Remove @djaglowski @codeboten they are part of @open-telemetry/collector-contrib-approvers
- Add @open-telemetry/go-maintainers @open-telemetry/collector-maintainers as owners as well, since we want the maintainers to be able to approve PRs like https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/135
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Update codeowners for chloggen

---

.chloggen/crosslinkErrSup.yaml
crosslink/cmd/root.go
crosslink/internal/crosslink.go
crosslink/internal/prune.go
go.mod
go.sum
internal/syncerror/known_sync_error.go
internal/syncerror/known_sync_error_test.go
internal/syncerror/known_sync_error_windows.go

Move logger.sync() method call to cobras `postRunSetup` and ignore `ENOTTY` error produced on unix systems. 
Fixes #190

[crosslink] Ignore known zap.logger.sync() errors

---

.chloggen/mm_printTags.yaml
multimod/README.md
multimod/cmd/tag.go
multimod/internal/tag/tag.go
multimod/internal/tag/tag_test.go

This PR removes the `--push` flag on `multimod tag`. As shown in issue #177 `push` required additional authentication to be set up since it did not natively read git credentials from the environment. Multiple options were discussed in #177. This PR implements the last suggestion which prints all tags separated by a newline. This `--print-tags` option can then be worked into existing repositories release process.
The `push` code has been removed from multimod. I believe the `os.exec` option is still possible but I have not had time to address it. This option provides a quick win while also removing bugged code. I suggest we reopen #157 which can be assigned and investigated in the future. 
Fixes #177 
```
bryaag@147ddac12c15 multimod % ./multimod tag --module-set-name tools --commit-hash …
```

[multimod] Remove tag push, print instead. 

---

.chloggen/semconv_add_only_flag.yaml
semconvgen/generator.go

semconvgen: add only flag to proccess only a specified type

---

.chloggen/fix_semconvgen.yaml
semconvgen/generator.go

semconvgen: relabel mounted files

---

.chloggen/use-go-embed-for-chloggen-template.yaml
chloggen/internal/chlog/context.go
chloggen/internal/chlog/summary.go
chloggen/internal/chlog/summary_test.go

[chloggen] Use go embed to embed the template file

---

crosslink/go.mod
dbotconf/go.mod
internal/tools/go.mod
multimod/go.mod
semconvgen/go.mod
versions.yaml

[chore] prepare v0.5.0

---

.github/workflows/create-dependabot-pr.yml
.github/workflows/scripts/dependabot-pr.sh

This is the same script that is used in the collector/collector-contrib repos to handle updating the dependencies and tidying the repository.

[chore] add github action to make updating dependencies easier

---

.github/workflows/create-dependabot-pr.yml
.github/workflows/scripts/dependabot-pr.sh

This works around the limitation that a PR created by an action doesn't trigger workflows automatically by using the opentelemetrybot's token. See https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot

[chore] use opentelemetrybot

---

.github/workflows/scripts/dependabot-pr.sh

This removes the need for the "Skip changelog" label and update the title to contain "[chore]". This works around the issue that opentelemetrybot doesnt have permission to edit a PR and add a label to it.

[chore] update dependabot pr script

---

.chloggen/otel-cap.yaml
semconvgen/generator.go

Correct capitalization of Otel to be OTel

---

.chloggen/crosslink-work.yaml
.gitignore
Makefile
crosslink/README.md
crosslink/cmd/root.go
crosslink/internal/common.go
crosslink/internal/config.go
crosslink/internal/graph.go
crosslink/internal/mock_test_data/testWork/go.work
crosslink/internal/mock_test_data/testWork/gomod
crosslink/internal/mock_test_data/testWork/testA/gomod
crosslink/internal/mock_test_data/testWork/testB/gomod
crosslink/internal/work.go
crosslink/internal/work_test.go

Fixes https://github.com/open-telemetry/opentelemetry-go-build-tools/issues/309
Towards https://github.com/open-telemetry/opentelemetry-go/issues/3964
`go.work` is honored by `gopls` language server so that develoeprs get better UX in tools like VSCode, Vim, Emacs etc
References:
- https://go.dev/ref/mod#workspaces
- https://go.dev/blog/get-familiar-with-workspaces
- https://go.dev/doc/tutorial/workspaces
Prior work: https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/308
Make `crosslink` to create/update the `use` in `go.work` file (if it exists).
Take notice that it will not harm any repositories which do not use Go workspaces. However developers could still use the functionality during development 😉 
```sh
make gowork
```
created following `go.work` file
```
go 1.19
use …
```

crosslink: Add work command

---

chloggen/cmd/cmd_test.go
chloggen/cmd/new.go
chloggen/cmd/new_test.go
chloggen/cmd/root.go
chloggen/cmd/root_test.go
chloggen/cmd/update.go
chloggen/cmd/update_test.go
chloggen/cmd/validate.go
chloggen/cmd/validate_test.go

This PR increases test coverage by executing cobra commands directly. It also some new test cases and further validates expected outputs and errors.

[chore][chloggen] Run tests end-to-end

---

chloggen/cmd/cmd_test.go
chloggen/cmd/new.go
chloggen/cmd/new_test.go
chloggen/cmd/root.go
chloggen/cmd/root_test.go
chloggen/cmd/update.go
chloggen/cmd/update_test.go
chloggen/cmd/validate.go
chloggen/cmd/validate_test.go
chloggen/internal/chlog/entry.go
chloggen/internal/chlog/entry_test.go
chloggen/internal/config/config.go
chloggen/internal/config/config_test.go

This PR follows #368 and #369 to further prepare the chloggen tool for the introduction of a repo-level configuration file.
- Rebrands the notion of a "Context" as a "Config", but stops short of actually introducing the config file.
- Creates a `chloggen/internal/config` package and moves former "Context" files into this package. 
- Moves `RepoRoot` to `cmd.repoRoot`. The function is related to the "Context" of the tool, but as a "Config", it makes more sense that the value is provided.
- Further normalize tests across sub functions.

[chore][chloggen] Rename 'Context' to 'Config' and move to dedicated package

---

.chloggen/chloggen-config-file-2.yaml
.chloggen/chloggen-config-file.yaml
chloggen/cmd/cmd_test.go
chloggen/cmd/new.go
chloggen/cmd/new_test.go
chloggen/cmd/root.go
chloggen/cmd/root_test.go
chloggen/cmd/update_test.go
chloggen/cmd/validate.go
chloggen/cmd/validate_test.go
chloggen/internal/chlog/entry.go
chloggen/internal/chlog/entry_test.go
chloggen/internal/config/config.go
chloggen/internal/config/config.tmpl
chloggen/internal/config/config_test.go

This PR introduces an optional repo-level configuration file for the chloggen tool. 
- Add a global `--config` flag that can be used to specify a config file.
- Removes the `chloggen-directory` flag, which is not used anywhere in our org. Instead, this value can be specified within the config file.
- Renames the `ChloggenDir` field to `ChlogsDir`, since it is no longer required that this directory be used for "meta" files, such as config and template.
- Ensures that "meta" files (config, template) are ignored when reading/deleting entries. This allows for these files to be placed in the chlogs dir, or not.
- Adds an example config file that can be copied into place when setting up a repo. In the future this can likely be handled by a `chloggen init` command.

[chloggen] Introduce repo-level config file

---

chloggen/cmd/cmd_test.go
chloggen/cmd/new_test.go
chloggen/cmd/root.go
chloggen/cmd/update_test.go
chloggen/cmd/validate_test.go
chloggen/internal/chlog/entry.go
chloggen/internal/config/config.go

This is a subset of #372 which will make that PR easier to review.

[chore] Cleanup chloggen globalCfg usage

---

.chloggen/semconvgen-quickfix.yaml
semconvgen/generator.go

This is "quickfix" for `semconvgen` so that the OTel Collector and Go can use `semconvgen` after the semantic conventions moved from https://github.com/open-telemetry/opentelemetry-specification to https://github.com/open-telemetry/semantic-conventions.
This change was tested as part of https://github.com/open-telemetry/opentelemetry-go/pull/4362
A more sophisticated way would be probably to have two args in  `semconvgen`; one for the Git repository and second for folder when the YAML definitions reside. However, I think that it may be not worth the effort and could introduce more problems than benefits (both OTel Collector and Go would need to update their semconv generation scripts).

semconvgen: Quickfix after semconv repo migration

---

chloggen/cmd/cmd_test.go
chloggen/cmd/new.go
chloggen/cmd/new_test.go
chloggen/cmd/update_test.go
chloggen/cmd/validate.go
chloggen/cmd/validate_test.go
chloggen/internal/chlog/entry.go
chloggen/internal/chlog/entry_test.go
chloggen/internal/config/config.go
chloggen/internal/config/config.yaml
chloggen/internal/config/config_test.go

This is intended as a quick follow up to #372. Mostly it just standardizes on the terms "entry/entries" instead of "chlog/chlogs".

Chloggen clarify termininology

---

.github/workflows/changelog.yml
.github/workflows/ci.yml
.github/workflows/create-dependabot-pr.yml

This is a defensive PR to update the minimum go version used in GHA workflows. The latest patch version contains security related fixes.

[chore] update go version used in workflows

---

.chloggen/codeboten_add-ignore-excluded.yaml
multimod/cmd/sync.go
multimod/internal/common/module_versioning.go
multimod/internal/common/versions.go
multimod/internal/sync/sync.go
multimod/internal/sync/sync_test.go

This allows users of the `sync` command to sync all modules in a monorepo, including those listed in the excluded-modules. This is useful for repositories where some modules may not yet be ready for releasing (therefore listed under excluded-modules) but their dependencies still need to be managed via multimod.

multimod: ignore `excluded-modules` when `-a` flag is enabled

---

.chloggen/permissions-with-no-execution.yaml
chloggen/cmd/new.go

When you use `chloggen new --config template.yaml --filename contribution.yaml` the generated file
has `0755` permission. Thus, it generates `yaml` files with **Execution** permission.
Maybe you folks have a purpose for doing it. Although, I didn't find any explanation for it. 
Therefore, from my perspective, it seems to be a "bug". Please close this PR in case I am wrong. 
This Pull Request updates the code in order to use the permission `0644` where we have:
* User: Write, Read, No Execution
* Group: No Write, Read, No Execution
* Others: No Write, Read, No Execution
I was writing [this Pull Request](https://github.com/open-telemetry/opentelemetry-collector/pull/8955) to Open Telemetry Collectors and realized that this tool (`chloggen`) was creating executable files under …

[chloggen] Update permissions of the generated files

---

.chloggen/multimod-fix-tagging-on-windows.yaml
multimod/internal/common/conversions.go
multimod/internal/common/tools.go
multimod/internal/common/tools_test.go

Fixes #464 
- `moduleFilePathToTagName()` produces the following on Windows due to Windows file path using backslashes instead of slashes.
```
could not retrieve tag names from module paths: could not convert module file paths to tag names: could not convert module file path to tag name: modFilePath C:\...\test\test1\go.mod not contained in repo with root C:\...\
```
- `filePathToRegex()` failing as `filepath.Separator()` in Windows is a backslash instead of the expected slash.
`multimod` unit test now passes on Windows with this PR

multimod: Fix tagging on Windows

---

.chloggen/codeboten_crosslink-skip.yaml
crosslink/README.md
crosslink/cmd/root.go
crosslink/cmd/root_test.go
crosslink/internal/config.go
crosslink/internal/crosslink_test.go
crosslink/internal/graph.go
crosslink/internal/mock_test_data/testSkip/gomod
crosslink/internal/mock_test_data/testSkip/testA/gomod
crosslink/internal/mock_test_data/testSkip/testB/gomod

This allows modules in monorepos to opt out of crosslink. This will be used in mdatagen in the Collector core repo for example, where mdatagen has dependencies on internal collector modules, but we don't want to use replace statements as it breaks the ability to `go install` mdatagen
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/9281

[crosslink] add --skip flag

---

.golangci.yml

> level=warning msg="[config_reader] The configuration option `run.skip-dirs-use-default` is deprecated, please use `issues.exclude-dirs-use-default`."
level=warning msg="[config_reader] The configuration option `output.format` is deprecated, please use `output.formats`"
level=warning msg="[config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`."

Fix all lint deprecations

---

.chloggen/mx-psi_multimod-modref.yaml
multimod/internal/common/tools.go
multimod/internal/common/tools_test.go
multimod/internal/common/versions.go
multimod/internal/prerelease/prerelease.go
multimod/internal/sync/sync.go

Fixes open-telemetry/opentelemetry-collector/issues/9827

[multimod] Resolve version for commit per module instead of per module set

---

chloggen/internal/chlog/entry_test.go
internal/repo/repo_test.go

The G301 rule was updated to check for `os.ModePerm` in v1.58.2: https://github.com/securego/gosec/pull/1138.
This unblocks the upgrade of Go linter from v1.58.1 to a later version.
Example of a failure on linter upgrade PR https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/574:
- https://github.com/open-telemetry/opentelemetry-go-build-tools/actions/runs/10355977808/job/28664809719

refactor: fix gosec linter G301 issue

---

.chloggen/mx-psi_better-multimod-errors.yaml
multimod/internal/sync/sync.go
multimod/internal/sync/sync_test.go

- Check status code of reply from Go proxy and fail if status code is 4xx or 5xx.
- Add information about package and tag that caused the failure

[multimod] Improve error message when Go proxy misbehaves

---

.github/workflows/changelog.yml

As the more recent versions are broken, and falsely fail the build.
See https://github.com/tcort/markdown-link-check/issues/369
Related: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36223

Pin markdown-link-check to 3.12.2

---

.chloggen/mowies-fix-chloggen-output.yaml
chloggen/cmd/root.go

Fixes #611
This PR sets the default output for `chloggen` to stdout as it would be set to stderr otherwise which has all kinds of issues that follow in the usage of the tool downstream.

fix: set default output of chloggen to stdout

---

versions.yaml

This excludes githubgen from the released modules, so 0.16.0 can be cut (https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/656) before the additional work on that module is finished (https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/655).

Exclude githubgen from released modules

---

githubgen/codeowners.go

Context in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37292
Currently, lines generated for unmaintained components in `.github/CODEOWNERS` have a trailing whitespace. This is a whitespace error. This removes the trailing whitespace.

[chore][githubgen] Remove unnecessary trailing whitespace

---

.chloggen/fix-issuegenerator-body.yaml
.chloggen/fix-issuegenerator-title.yaml
issuegenerator/main.go

An oversight while working on https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/720. It turns out I forgot to update one place.
We noticed while rolling out the automation in the contrib repository: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39585
cc @mx-psi

Print the correct workflow link in issue body

---

.chloggen/fix-issuegenerator-title.yaml
issuegenerator/main.go

Another problem we noticed while rolling this out. Our "Ping codeowners" automation doesn't work for the full module name, so we're trimming it.
Also caught upstream: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39585

Trim repository name from Issue title

---

.chloggen/trim_issue_title.yaml
issuegenerator/main.go
issuegenerator/main_test.go

When checking to see if an existing issue is already open for a failed test module, the module name is trimmed to remove the github repo prefix of `github.com/githubOwner/githubRepository/`. However, when creating an issue, the entire module name is being used. Names need to be consistent to ensure duplicates are not filed, and frequency is added to existing issues when necessary. This fixes them to be consistent.
Resolves https://github.com/open-telemetry/opentelemetry-go-build-tools/issues/861

[issuegenerator] Trim module name when creating a new issue

---

.chloggen/include-test-failure-message.yaml
issuegenerator/main.go
issuegenerator/main_test.go

After some feedback[[1](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40331#issuecomment-2914022459)][[2](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/41354#issuecomment-3104680165)], I'm also adding the test failure messages in the comments so people don't need to hunt them down

issuegenerator: Include test failure messages in Issue comments

---

.chloggen/chloggen-yml-support.yaml
chloggen/internal/chlog/entry.go
chloggen/internal/chlog/entry_test.go

Fixes #1079.
Adds support for reading and deleting entries that end up with `.yml` so that YAML files with this alternative extension are properly processed into the changelog.

[chloggen] Accept entries with `.yml` extension
